// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func root() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Da Wall</title><link rel=\"stylesheet\" href=\"/public/css/style.css\"><script src=\"/public/js/htmx.min.js\"></script></head><body><header><h1>Wall of posts</h1></header><main hx-target=\"#posts-container\" hx-swap=\"innerHtml transition:true\"><section><form hx-post=\"/posts\" hx-on::after-request=\"this.reset()\"><textarea placeholder=\"lorem ipsum...\" class=\"form-textarea\" name=\"post_text\" minlength=\"1\"></textarea> <button class=\"form-button\" type=\"submit\">Create post</button></form></section><hr><section hx-get=\"/posts\" hx-trigger=\"load, every 5s\"><h3>Previous posts</h3><h3 class=\"htmx-indicator\">Loading...</h3><div id=\"posts-container\"></div></section></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
